DATASETS:
  TEST:
  - GEBD_val
  TRAIN:
  - GEBD_train
DIFFUSION:
  BETA_SCHEDULE: cosine
  CFG_PROB: 0.1
  CFG_SCALE: 4.0
  DDIM_SAMPLING_ETA: 0.0
  DETERMINISTIC: false
  SAMPLING_TIMESTEPS: 8
  SNR_SCALE: 1.0
  TIMESTEPS: 1000
  VALIDATION_TIMESTEPS:
  - 8
INPUT:
  ANNOTATORS: 4
  ANNOTATOR_SELECT: best
  ARGUMENT: true
  DOWNSAMPLE: 3
  DYNAMIC_DOWNSAMPLE: false
  END_TO_END: true
  FRAME_PER_SIDE: 5
  GAUSSIAN_TARGET: false
  GAUS_SIGMA: 0.8
  ONLY_TARGET_GAUS: true
  RESOLUTION: 224
  SEQUENCE_LENGTH: 100
MODEL:
  BACKBONE:
    FREEZE: false
    NAME: resnet50
  CLASS_DIM: 1
  DECODER: transformer
  DIMENSION: 512
  ENCODER: basicGEBD
  ENCODER_OUT: false
  FEED_FORWARD_DIM: 2048
  FPN_START_IDX: 3
  HEAD_CHOICE: 3
  NAME: DiffusionMSE_CFG
  NUM_HEADS: 8
  NUM_LAYERS: 6
  SYNC_BN: true
  WINDOW_SIZE: 17
OUTPUT_DIR: output/e2e_MSE_CFGp0.1s4.0_condD_targetgaus0.8_t100_d512_B2_ann4_lr2e-5
SOLVER:
  AMPE: true
  BATCH_SIZE: 2
  CLIP_GRAD: 0.0
  GAMMA: 0.1
  LR: 2.0e-05
  MAX_EPOCHS: 100
  MILESTONES:
  - 2
  - 3
  MOMENTUM: 0.9
  NUM_WORKERS: 8
  OPTIMIZER: AdamW
  SCHEDULER: cosine
  WARMUP: true
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.0001
TEST:
  PRED_FILE: ''
  PROTOCOL: max
  RELDIS_THRESHOLD: 0.05
  THRESHOLD: 0.5
